export const SELECT_APPLICATION = "SELECT_APPLICATION";
export const FETCH_APPLICATION = "FETCH_APPLICATION";
export const SET_APPLICATION = "SET_APPLICATION";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const CHANGE_FROM_COORDINATE = "CHANGE_FROM_COORDINATE";
export const CHANGE_TO_COORDINATE = "CHANGE_TO_COORDINATE";